// Image imports
export { default as about1 } from './about1.png';
export { default as about2 } from './about2.png';
export { default as about3 } from './about3.png';
export { default as kolam_Analysis } from './kolam_Analysis.png';
export { default as Kolam_Gen1 } from './Kolam_Gen1.png';
export { default as Kolam_Gen2 } from './Kolam_Gen2.png';
export { default as Kolam_Gen3 } from './Kolam_Gen3.png';
export { default as Kolam_Gen4 } from './Kolam_Gen4.png';
export { default as Kolam_Gen5 } from './Kolam_Gen5.png';
export { default as Kolam_Gen6 } from './Kolam_Gen6.png';
export { default as Kolam_Gen7 } from './Kolam_Gen7.png';
export { default as kolam_viewer } from './kolam_viewer.png';
export { default as kolan_gallery1 } from './kolan_gallery1.png';
export { default as kolgal2 } from './kolgal2.png';
export { default as kolgal3 } from './kolgal3.png';
export { default as kolgal4 } from './kolgal4.png';
export { default as kolgal5 } from './kolgal5.png';
export { default as kolgal6 } from './kolgal6.png';
export { default as kolgal7 } from './kolgal7.png';
export { default as kolgal8 } from './kolgal8.png';
export { default as kolgal9 } from './kolgal9.png';
export { default as kolgal10 } from './kolgal10.png';
export { default as kolgal11 } from './kolgal11.png';
export { default as kolgal12 } from './kolgal12.png';
export { default as patreco1 } from './patreco1.png';
export { default as patreco2 } from './patreco2.png';
export { default as pattrule1 } from './pattrule1.png';
export { default as pattrule2 } from './pattrule2.png';
export { default as redraw_kolam } from './redraw_kolam.png';
export {default as logo} from './logo.png';
export {default as f1} from './profile_icon/f1.png';
export {default as kolamRedraw} from './kolamRedraw.png';
export {default as rangoli} from './rangoli.png';
export {default as KolamGenerator} from './KolamGenerator.png';